# Debug dans la console
debug: false

# Permet de debug SQL
sql-debug: false

# Si le clic est trop rapide, on ne va pas le prendre en compte (500ms).
minimum-delay: 500

# Fin de la session (50 ticks, 2.5s).
# Permet de mettre fin à la session de clic sur joueur pour une analyse postérieure.
session-end-after: 50

# Temps minimum de session (60 secondes).
minimum-session-duration: 60000 # 60 secondes

# Nombre de clics minimum dans la session
minimum-session-clicks: 40

# On supprime le 5% les plus hauts et les plus bas
remove-percent: 0.05

# Si une session a un écart type inférieur ou égal à 20.0, alors le joueur est suspect.
session-is-normal: 20.0