# Debug dans la console
debug: false

# Storage:
# SQLITE - For the launch of the plugin only.
# HIKARICP - RECOMMENDED - HikariCP is a fast and lightweight JDBC connection pool. It optimizes database connections, ensuring quick acquisition and low latency. This improves performance and reliability, making it ideal for high-demand applications.
#
# We advise you to use HIKARICP, the SQLITE storage is only there to install the plugin and do some tests, not all features are available with SQLITE yet.
# The plugin will work, but some features like sanctions update when launching the plugin will not work.
# This will be fixed in future plugin updates
storage-type: SQLITE

# Configuration of your database, it is recommended to use the database to store your data.
database-configuration:
  # The prefix that will be applied to all tables,
  # if you have several plugins with the same database, you must have one.
  # It is advisable not to change this value
  table-prefix: "zantiautoclick_"
  # IP Address of the machine the database is hosted on
  host: 192.168.10.10
  # Port of the database, by default, MYSQL's port is 3306
  port: 3306
  # Database username
  user: homestead
  # Database password
  password: 'secret'
  # Database
  database: zantiautoclick
  # Enable of not the SQL debug mode
  debug: true

# Si le clic est trop rapide, on ne va pas le prendre en compte (500ms).
minimum-delay: 500

# Fin de la session (50 ticks, 2.5s).
# Permet de mettre fin à la session de clic sur joueur pour une analyse postérieure.
session-end-after: 50

# Temps minimum de session (60 secondes).
minimum-session-duration: 60000 # 60 secondes

# Nombre de clics minimum dans la session
minimum-session-clicks: 40

# On supprime le 5% les plus hauts et les plus bas
remove-percent: 0.05

# Si une session a un écart type inférieur ou égal à 20.0, alors le joueur est suspect.
session-is-normal: 20.0