debug: false

# Storage:
# SQLITE - For the launch of the plugin only.
# HIKARICP - RECOMMENDED - HikariCP is a fast and lightweight JDBC connection pool. It optimizes database connections, ensuring quick acquisition and low latency. This improves performance and reliability, making it ideal for high-demand applications.
#
# We advise you to use HIKARICP, the SQLITE storage is only there to install the plugin and do some tests, not all features are available with SQLITE yet.
# The plugin will work, but some features like sanctions update when launching the plugin will not work.
# This will be fixed in future plugin updates
storage-type: SQLITE

# Configuration of your database, it is recommended to use the database to store your data.
database-configuration:
  # The prefix that will be applied to all tables,
  # if you have several plugins with the same database, you must have one.
  # It is advisable not to change this value
  table-prefix: "zantiautoclick_"
  # IP Address of the machine the database is hosted on
  host: 192.168.10.10
  # Port of the database, by default, MYSQL's port is 3306
  port: 3306
  # Database username
  user: homestead
  # Database password
  password: 'secret'
  # Database
  database: zantiautoclick
  # Enable of not the SQL debug mode
  debug: true


# Session configuration
session:

  # If the click is too fast, it will not be considered (500ms).
  minimum-delay: 500

  # End of session (50 ticks, 2.5s).
  # Allows ending the click session on player for later analysis.
  end-after: 50

  # Minimum session duration (60 seconds).
  minimum-duration: 60000 # 60 seconds

  # Minimum number of clicks in the session
  minimum-clicks: 40

# Session analysis
analyze:

  # Percentage of the session to trim from the ends (e.g., 0.1 = 10%)
  session-trimmed: 0.1

  # Maximum difference between two clicks to be considered a small variation (in ms)
  small-variation: 10

  # Minimum difference between two clicks to be considered a large jump (in ms)
  large-variation: 200

  # Minimum score to consider the session accepted
  required-score: 60.0

  # Parameters for score calculation:

  scoring:
    # Influence of small variations
    small-variation:
      threshold-percent: 50.0   # Percentage at which points start to be awarded
      multiplier: 0.5           # Points added per percentage above the threshold
      max-bonus: 25.0           # Maximum possible bonus

    # Influence of the range
    range:
      relative-threshold: 0.3   # % of the average to define a small range
      max-bonus: 25.0           # Maximum possible bonus

    # Influence of the standard deviation
    stddev:
      relative-threshold: 0.1   # % of the average to define a low standard deviation
      max-bonus: 20.0           # Maximum possible bonus

    # Influence of the frequency of the most common click
    top1-frequency:
      threshold-percent: 10.0   # Percentage at which points start to be added
      multiplier: 0.5           # Points added per percentage above the threshold

    # Influence of the sum of the three most frequent clicks
    top3-frequency:
      threshold-percent: 30.0   # Percentage at which points start to be added
      multiplier: 0.3           # Points added per percentage above the threshold

    # Bonus if no large jump is detected
    no-large-jump-bonus: 15.0

  # Maximum possible score (do not exceed)
  max-score: 100.0