name: zAntiAutoClick
version: '1.0.2'
main: fr.maxlego08.autoclick.ZClickPlugin
api-version: '1.20'
authors: [ Maxlego08 ]
description: Anti Auto Click
website: https://groupez.dev/
depends:
  - packetevents
  - zMenu